# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Broombroom' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Broombroom
	pod 'CircleProgressBar', '~> 0.32’
	pod 'Parse'
	pod 'ParseUI'
	pod 'MBProgressHUD'
	pod 'DZNEmptyDataSet'
	pod 'THCalendarDatePicker', '~> 1.2.6'
	pod 'STPopup'
	pod 'LCModal', '~> 1.0'

  target 'BroombroomTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BroombroomUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
